# This file was generated by GoReleaser. DO NOT EDIT.
cask "nsa" do
  version "1.0.1"

  on_macos do
    on_arm do
      sha256 "f5e08f59aab00302b7087b7d2cca8655b28d13159fdd835c25398bf59251ea67"
      url "https://releases.nsa.tech/#{version}/nsa_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "acb150b434a2eff203f519e29c48ef67150ac49b4876670b0726ad39befb727f"
      url "https://releases.nsa.tech/#{version}/nsa_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "197111d3da264037d58a0f96c59f8fdfc8203fc4089974d2c09090de4c08b467"
      url "https://releases.nsa.tech/#{version}/nsa_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "73127b12e9f1c81120c0aae21f7d3464cf6e5dfcdf8e39ed932e1e01dc47488a"
      url "https://releases.nsa.tech/#{version}/nsa_#{version}_linux_amd64.tar.gz"
    end
  end

  name "nsa"
  desc "Peer-to-peer networking between your own machines."
  homepage "https://nsa.tech"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nsa"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/nsa"]
    end
  end

  # No zap stanza required
end
